#pragma once

enum _E_CMD_TYPE
{
	E_CMD_GET_FILE = 0,
	E_CMD_GET_DIRECTORY ,
	E_CMD_GET_FILE_LIST, 

	E_CMD_SEND_FILE = 100, 
	E_CMD_SEND_DIRECTORY,
	E_CMD_SEND_FILE_LIST,

    E_CMD_RESTART_COMPUTER = 200,
    E_CMD_START_IE ,
};