#define MAJOR_VERSION	1
#define MINOR_VERSION	3
#define MICRO_VERSION	5
#define BUILD_VERSION	60

#define QUOTE_(x)		#x
#define QUOTE(x)		QUOTE_(x)

#define VERSION_STRING	QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION.BUILD_VERSION)
#define VERSION_STRING_W	_T(QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION.BUILD_VERSION))

#define BUILD_DATE		02/09/2013 21:13:10
#define BUILD_DATE_STRING	_T(QUOTE(BUILD_DATE))
