// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

#ifndef PROTOBUF_MessageProto_2eproto__INCLUDED
#define PROTOBUF_MessageProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#include "../comDll.h"
#pragma warning(disable:4275)

//////////////////////////////////////////////////////////////////////////

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "msgFile.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageProto_2eproto();
void protobuf_AssignDesc_MessageProto_2eproto();
void protobuf_ShutdownFile_MessageProto_2eproto();

class MessageProto;

// ===================================================================

class MessageProto : public ::google::protobuf::Message {
 public:
  MessageProto();
  virtual ~MessageProto();

  MessageProto(const MessageProto& from);

  inline MessageProto& operator=(const MessageProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageProto& default_instance();

  void Swap(MessageProto* other);

  // implements Message ----------------------------------------------

  MessageProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageProto& from);
  void MergeFrom(const MessageProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 cmdType = 1;
  inline bool has_cmdtype() const;
  inline void clear_cmdtype();
  static const int kCmdTypeFieldNumber = 1;
  inline ::google::protobuf::int32 cmdtype() const;
  inline void set_cmdtype(::google::protobuf::int32 value);

  // repeated .MsgFile msgFileData = 2;
  inline int msgfiledata_size() const;
  inline void clear_msgfiledata();
  static const int kMsgFileDataFieldNumber = 2;
  inline const ::MsgFile& msgfiledata(int index) const;
  inline ::MsgFile* mutable_msgfiledata(int index);
  inline ::MsgFile* add_msgfiledata();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgFile >&
      msgfiledata() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgFile >*
      mutable_msgfiledata();

  // @@protoc_insertion_point(class_scope:MessageProto)
 private:
  inline void set_has_cmdtype();
  inline void clear_has_cmdtype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::MsgFile > msgfiledata_;
  ::google::protobuf::int32 cmdtype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MessageProto_2eproto();
  friend void protobuf_AssignDesc_MessageProto_2eproto();
  friend void protobuf_ShutdownFile_MessageProto_2eproto();

  void InitAsDefaultInstance();
  static MessageProto* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageProto

// required int32 cmdType = 1;
inline bool MessageProto::has_cmdtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageProto::set_has_cmdtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageProto::clear_has_cmdtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageProto::clear_cmdtype() {
  cmdtype_ = 0;
  clear_has_cmdtype();
}
inline ::google::protobuf::int32 MessageProto::cmdtype() const {
  return cmdtype_;
}
inline void MessageProto::set_cmdtype(::google::protobuf::int32 value) {
  set_has_cmdtype();
  cmdtype_ = value;
}

// repeated .MsgFile msgFileData = 2;
inline int MessageProto::msgfiledata_size() const {
  return msgfiledata_.size();
}
inline void MessageProto::clear_msgfiledata() {
  msgfiledata_.Clear();
}
inline const ::MsgFile& MessageProto::msgfiledata(int index) const {
  return msgfiledata_.Get(index);
}
inline ::MsgFile* MessageProto::mutable_msgfiledata(int index) {
  return msgfiledata_.Mutable(index);
}
inline ::MsgFile* MessageProto::add_msgfiledata() {
  return msgfiledata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgFile >&
MessageProto::msgfiledata() const {
  return msgfiledata_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgFile >*
MessageProto::mutable_msgfiledata() {
  return &msgfiledata_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageProto_2eproto__INCLUDED
